name: Deploy Smart Lamp Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**' 
      - '.github/workflows/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Lấy code từ repo
      uses: actions/checkout@v3

    - name: Đăng nhập vào Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Đóng gói và đẩy Image lên kho (Build & Push)
      uses: docker/build-push-action@v4
      with:
        context: ./backend 
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/smart-lamp-backend:latest

    - name: Gọi qua VPS để tải và chạy code mới
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}          
        username: ${{ secrets.VPS_USERNAME }} 
        key: ${{ secrets.VPS_SSH_KEY }}       
        script: |
          cd smart-lamp/backend
          
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/smart-lamp-backend:latest
          
          sudo docker stop backend_prod || true
          sudo docker rm backend_prod || true
          
          sudo docker run -d --name backend_prod -p 8000:8000 --env-file .env ${{ secrets.DOCKER_USERNAME }}/smart-lamp-backend:latest